version: '3.8'

services:
  frontend:
    build:
      dockerfile: Dockerfile
    container_name: portfolio-frontend
    restart: always
    ports:
      - "4200:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
